name: Semgrep Code Scan
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write # Для загрузки SARIF в Security tab

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python # Требуется для запуска Semgrep
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep
        run: |
          semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_RULES: p/default # Встроенные правила (default, security, ci и т.д.)
          # SEMGREP_RULES: .github/semgrep-rules.yml  # Раскомментируй для кастомных правил
        continue-on-error: true # Продолжить для загрузки SARIF даже при ошибке
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
