name: Dockerfile Lint
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # Ручной запуск через GitHub UI

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile # Путь к Dockerfile
          # config: .hadolint.yaml  # Раскомментируй для кастомных правил
          failure-threshold: warning # Фейл CI на warning и выше (info, warning, error)
