image-name := "myimage"
container-name := "mycontainer"
port := "3000"

build:
    docker build -t {{image-name}}:latest  .

run:
    docker run -d --name {{container-name}} -p {{port}}:{{port}} {{image-name}}:latest

check:
    sleep 5
    docker ps -a
    docker logs {{container-name}}
    curl -f http://localhost:{{port}}/
    docker inspect --format='{{{{json .State.Health.Status}}}}' {{container-name}}

stop:
    docker stop {{container-name}}
    docker rm {{container-name}}
