container-name := "next-container"
image-name := "myapp"

build:
    docker build -t {{image-name}}:latest  .

run:
    docker run -d --name {{container-name}} -p 3000:3000 {{image-name}}:latest

check:
    sleep 5
    docker ps -a
    docker logs {{container-name}}
    curl -f http://localhost:3000/
    docker inspect --format='{{{{json .State.Health.Status}}}}' {{container-name}}

stop:
    docker stop {{container-name}}
    docker rm {{container-name}}
